### ISSUE TITLE
Add ingame version info

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#111]
To help with identifying issues, it would be a good idea to have a version field (preferrably inside settings) that shows the Trajectories mod version.

**Comment by PiezPiedPy** [comment]
Good idea, I'll add it to both Gui's ;)

**Comment by fat-lobyte** [comment]
Thanks!

**Comment by PiezPiedPy** [comment]
Implemented into the NewGui.
I added the version string to the Title to save screen space, originally put it in the bottom left corner.
Also I've referenced the Assembly info so no extra field to bump on version changes.
