### ISSUE TITLE
Allow setting default descent profile to retrograde

### ISSUE THREAD

**Issue by strudo76** [neuoy/KSPTrajectories#112]
Is it possible to change the configuration so that the retrograde decent profile option is selected by default. At my early stage of the game, I'm exclusively using the retrograde option, so it would be good to have that option automatically selected instead of having to open the interface every time to tick the box.

Thanks

**Comment by PiezPiedPy** [comment]
Good idea.

Anyone got any preferences to where the option should go, I'm thinking a radio button on the setting page of the Gui would probably be the best option.

I'm also planning on making the descent profile persistent and separate for each craft. i.e. you switch to another craft and the profile will change to what was set for that craft.

And I've just had a brainwave 😃 maybe have a default descent profile that can be set by the user and is used for new constructed crafts, no idea where to put the settings yet, maybe a popup box called from the descent or settings page on the Gui or a text file in the Trajectories folder.

**Comment by fat-lobyte** [comment]
> I'm also planning on making the descent profile persistent and separate for each craft. i.e. you switch to another craft and the profile will change to what was set for that craft.

That sounds good!

> Anyone got any preferences to where the option should go, I'm thinking a radio button on the setting page of the Gui would probably be the best option.

My preference is to actually hide the option away in the settings file that is currently  `Trajectories/Plugin/PluginData/Trajectories/config.xml` (And maybe also change the location of that file :roll_eyes: ). There's not a whole lot of point to make this option super visible, because we already have the visible settings for the descent profile. With persistency, people can just use that.

I do think we should set this default to Retro, though.

**Comment by neuoy** [comment]
I'm not sure to follow you about storing the profile per-craft ; it's supposed to work already, and also to be persisted in save files. It's stored in a module added to every command module, and duplicated if a ship has more than one. This way, when you separate the ship, each subship gets the same profile (until you eventually change them of course). The ModuleManager dependency is there only for this feature.

Unless there is a bug?

**Comment by PiezPiedPy** [comment]
>My preference is to actually hide the option away in the settings file that is currently  GameData/Trajectories/Plugin/PluginData/Trajectories/config.xml (And maybe also change the location of that file, it's annoying me how deep it is buried).

Same here but I think KSP puts it there, hope we can move it, if not we can do a bit of sneaky and copy the file into the Trajectories main folder in the Load and Save methods of the settings class.

>I'm not sure to follow you about storing the profile per-craft ; it's supposed to work already

Could be a bug in my new Gui, I've just started coding the Descent page. I'll do a build from neuoy/master and see what happens ;)

**Comment by neuoy** [comment]
Right, I forgot you were working on the new GUI, sorry, I follow the discussions from very far :-) Well maybe my comment can still help you to understand the previous system :-) Don't hesitate to ask if some old code is too obscure (in the hope I can still understand what I wrote ages ago ;-) )

**Comment by fat-lobyte** [comment]
Well if we already have persistency on a per-craft basis, then we don't need to re-implement it! It's not really dependent on the GUI if I understand correctly.

**Comment by neuoy** [comment]
No, but the GUI might need to be aware of it to correctly update itself on ship change or save load

**Comment by PiezPiedPy** [comment]
Yep the Gui will have to watch, update any changes or respond to/from the module.
@neuoy do you know what class/method handles the module, saves me looking through the code 😉

**Comment by PiezPiedPy** [comment]
Should I go ahead and set the default descent profile to Retro ?
I will add a toggle to the NewGui settings page at a later date so users can decide what they would prefer to use.

**Comment by fat-lobyte** [comment]
> Should I go ahead and set the default descent profile to Retro ?

Yes please. I think most people do that anyway.

**Comment by PiezPiedPy** [comment]
Changed the default to Retrograde but will only be available when the NewGui is merged.

**Comment by PiezPiedPy** [comment]
I've added a radio button to the settings page to allow setting the descent profile to a user default of prograde or retrograde on vessel launch.
