### ISSUE TITLE
Target Distance Readout incorrect on worlds other than Kerbin

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#118]
I tried targeting Waypoints on Gilly and on Eve, and get a distance readout from them. When the targeting cross was on the Waypoint (and later landing confirmed a correct landing prediction), the Readout was hundreds (Gilly) or thousands (Eve) kilometers off.

My hunch is that there is some hardcoded value that uses the Kerbin radius or something for the distance readout.

**Comment by PiezPiedPy** [comment]
I'm right in the middle of doing the Targeting page on the NewGUI. I'll take note and see if I can find the bug along the way ;)

**Comment by fat-lobyte** [comment]
I can't even reproduce this anymore. Closing until I can.
