### ISSUE TITLE
High deviation using FAR

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#125]
Testing current master 21843ad853c8db45e4c52931021d1d8364aa7d99 with Ferram Aerospace Reasearch v0.15.9_Liebe causes high deviation from predicted target.

Test case kerbin-half: -121 km

**Comment by fat-lobyte** [comment]
Force directions seem to be OK:

![far_forces-angle_predicted-actual](https://user-images.githubusercontent.com/173609/35246247-5a31ea8e-ffc6-11e7-80e9-e6f91be03bf0.png)

Angle between forces is in the range of 1e-6, that should be just slightly above numeric precision and should be considered zero.

**Comment by fat-lobyte** [comment]
Still talking about the kerbin-half testcase:

Deviation increases from Atmospheric entry to about 50 km, then it starts going down again.

Coincides with the difference in predicted vs actual force:

![far_forces-difference_predicted-actual](https://user-images.githubusercontent.com/173609/35248456-76216bae-ffce-11e7-9712-d001465ba39c.png)

**Comment by fat-lobyte** [comment]
The code in [Trajectory.DebugTelemetry()](https://github.com/neuoy/KSPTrajectories/blob/4c61ea1b99432f43cc6bd2849d6a381f7b833a8a/Plugin/Trajectory.cs#L345) looks a bit suspicious, so I'm a little afraid that the data that I'm reading with the Telemetry is not what is actually calculated.

Especially this looks suspicous to me:

    TotalForce += bodySpaceVelocity * (dt * 0.000015); // numeric precision fix

**Comment by skrelk** [comment]
This bug doesn't occur in the current version, FYI

**Comment by fat-lobyte** [comment]
@dlrk2 

Huh? Are you saying there is no Drift when using FAR? Which FAR version and which KSP version exactly?

**Comment by dlrk2** [comment]
KSP 1.3.1 and the latest FAR dev build. I have to do a little bit of maneuvering (pitching a yawing 1-5 degrees following the navball dot), but I get within .5km of where I want to be.

**Comment by fat-lobyte** [comment]
@dlrk2 Where can I get the latest FAR dev build? I can't find a pre-Release on GitHub or any download link in the FAR thread.

**Comment by dlrk2** [comment]
The Dec 18, 2017 commit from the master branch on the FAR repository. It's pre-compiled in the gamedata/ferramaerospaceresarch folder

**Comment by fat-lobyte** [comment]
Still broken for me, unfortunately 😞

**Comment by dlrk2** [comment]
Would it help if I sent a video of a reentry?

**Comment by fat-lobyte** [comment]
> Would it help if I sent a video of a reentry?

Yes, actually! And your Trajectories version, is it 2.0.0?

**Comment by dlrk2** [comment]
Alright, will do! It's 2.0.0 Trajectories, that FAR dev build and 1.3.1 KSP. I'll link a video of a suborbital flight from a Falcon style stage (I have to overshoot a bit for that to work right), and a pod reentry.

**Comment by dlrk2** [comment]
So, I did a few more tests, and it looks like the deviation is there, I've just been correcting for it with lift by pitching up. I had assumed that it was normal to have to do that, tbh. 

So, whoops!

**Comment by dlrk2** [comment]
Just a suggestion, and I apologize if this doesn't make sense, but if the difference between the predicted and actual force is obvious, maybe just add a correction factor?

**Comment by fat-lobyte** [comment]
> Just a suggestion, and I apologize if this doesn't make sense, but if the difference between the predicted and actual force is obvious, maybe just add a correction factor?

The difference is not constant, and it's only obvious after we have actually flown and landend and recorded it. Considering we're in the prediction business here, I'd say that's a bit too late ;)

**Comment by dlrk2** [comment]
Indeed. Well, let me know if theres any testing I can do that will help.

**Comment by dlrk2** [comment]
And, in case it helps, pitching up slightly, especially at the upper and midatmosphere corrects pretty well.

**Comment by dlrk2** [comment]
IMO this issue is pretty much resolved. I just landed right on top of the space center from Minmus orbit with FAR. Very slight pitching (+/- 1 degree) is needed to be precise, but that's a non-issue.

**Comment by fat-lobyte** [comment]
> IMO this issue is pretty much resolved. I just landed right on top of the space center from Minmus orbit with FAR. Very slight pitching (+/- 1 degree) is needed to be precise, but that's a non-issue.

Interesting. Could you post your game version, your FAR version, your Trajectories version and maybe a craft file? I'd be very curious about that.

**Comment by efokschaner** [comment]
I'm seeing a possibly related precision issue:
- KSP 1.10.1.2939
- FAR 0.15.11.4
- Trajectories 2.3.4
I just tried out Trajectories for the first time and I had 3 similar flights all show the same symptoms:
The craft is a KV-2 ‘Pea’ Reentry Module with some flat solar panels and a Mk16 parachute, on return trajectory from Minmus, with perikee ~30-35 km, re-entry speed is around 3400 m/s.
Trajectories predicts the vessels leaving the atmosphere with relatively little reduction in energy.
In actuality, the vessels are reliably slowed down and do not re-emerge from the atmosphere.
Trajectories is configured to retrograde and we hold retrograde during re-entry, not that it ought to matter much with these spherical command modules.

**Comment by PiezPiedPy** [comment]
I've heard that these re-entry modules have a different drag cube than the other modules, I would suspect the problem is with the drag cubes. Hopefully I might be able to find out what the issue is since I am currently going through the prediction code in an attempt to multithread the code, time will tell, until then I don't think there is much I can do about the situation 😞

**Comment by 7ranceaddic7** [comment]
If these have a pre-specified dragcube defined in the PART{}, you can comment out /delete the DRAGCUBE{} section to have KSP auto-generate one. Then, compare the provided original with the KSP-created version stored in `partconfig.cfg` (located in ksproot).

**Comment by efokschaner** [comment]
Thanks @PiezPiedPy , if you're aware of an issue specifically with the re-entry command module this gives me some hope that I might be able to get better results with some "higher-stakes" aerobraking I was about to try out on a different ship.

As this issue is potentially re-entry command module-specific, would you like me to open a new issue on the repo?

Note: I come to the issues section with no expectation of maintainers fixing anything, only to catalogue the known issues such that others can be aware of limitations and get confirmation around issues they're seeing.

**Comment by fat-lobyte** [comment]
With newer versions of FAR, KSP and Trajectories, this is much improved.

In the kerbin-half test case, I landed 30 km off target which is already much better than 121 km. I consider this pretty decent because in that test case we skim the upper atmosphere for a long time where predictions are super sensitive to errors.

When the trajectory is shorter (About a quarter arc), the deviation was only 1.6 km.

I'm therefore closing this issue.
