### ISSUE TITLE
Lag spikes/stuttering with Trajectories and FAR

### ISSUE THREAD

**Issue by aluc24** [neuoy/KSPTrajectories#126]
KSP 1.3.1, x64
Trajectories 1.7.1.0
FAR 0.15.9, with cubes
Tons of other unrelated mods

Description: when a vessel is reentering in Kerbin's atmosphere in retrograde direction, lag spikes occur every ~2 seconds. At the same time, log spams message "Trajectories: Initializing cache" every ~2 seconds as well. Other angles of attack seem to produce less stuttering. This appears to happen with any kind of vessel that is capable of holding retrograde direction during reentry.

[ksp.log](https://github.com/neuoy/KSPTrajectories/files/1653602/ksp.log)

**Comment by fat-lobyte** [comment]
Could you provide me with a quicksave file that I can load with only stock parts?  Note that GitHub might prevent you from uploading the `.sfs` file directly, but you can rename it to `.sfs.txt` and it should be fine.

**Comment by fat-lobyte** [comment]
User mentioned in the Forum that the bug might have been a fluke.

Closing until further info arrives

https://forum.kerbalspaceprogram.com/index.php?/topic/162324-13-trajectories-v171-2017-10-13-atmospheric-predictions/&do=findComment&comment=3283365
