### ISSUE TITLE
v2.0.0 install issue

### ISSUE THREAD

**Issue by blkirk** [neuoy/KSPTrajectories#132]
I downloaded and installed v2.0.0 onto KSP 1.3.1.1891 (WindowsPlayer x64).  I restarted KSP a couple times and am not able to get it to work.

**C:\Kerbal Space Program\GameData>dir Trajectories**
 Volume in drive C has no label.
 Volume Serial Number is A250-AC72

 Directory of C:\Kerbal Space Program\GameData\Trajectories

02/28/2018  08:29 AM    <DIR>          .
02/28/2018  08:29 AM    <DIR>          ..
02/28/2018  08:29 AM             1,356 License.txt
02/28/2018  08:29 AM    <DIR>          Localization
02/28/2018  08:34 AM    <DIR>          Plugin
02/28/2018  08:29 AM             1,974 README.md
02/28/2018  08:29 AM    <DIR>          Textures
02/28/2018  08:29 AM               211 Trajectories.cfg
02/28/2018  08:29 AM               419 Trajectories.version
               4 File(s)          3,960 bytes
               5 Dir(s)  96,970,522,624 bytes free

C:\Kerbal Space Program\GameData>

Then restart KSP, and run this with a test ship with kOS:
if ADDONS:TR:AVAILABLE {
    if ADDONS:TR:HASIMPACT {
        PRINT ADDONS:TR:IMPACTPOS.
    } else {
        PRINT "Impact position is not available".
    }
} else {
    PRINT "Trajectories is not available.".
}

It always returns "Trajectories is not available.\nProgram has ended".
Any ideas?

**Comment by blkirk** [comment]
Forgot to add:
- No errors on startup
- No previous version of Velocities installed.
- The Velocities GUI seems to work correctly, maybe there was an internal/API change such that kOS can't talk to it anymore?

**Comment by neuoy** [comment]
Hi blkirk,

Is this the same issue as #131 ?

**Comment by PiezPiedPy** [comment]
@blkirk kOS have to update their code to comply with the Trajectories v2 API
see issue #131 that neuoy mentioned.

**Comment by PiezPiedPy** [comment]
Closed, Same issue as #131
