### ISSUE TITLE
Save window position

### ISSUE THREAD

**Issue by Brusura** [neuoy/KSPTrajectories#138]
after a KSP restart the window position is lost

OUTPUT_LOG:
https://drive.google.com/open?id=0B4kd548FeSEpTnRSSWtLVHVsNzA

KSP:
1.3.1 x64 en ( stock cubes )

Trajectories 2.0.0

Mod list ( sorry for the long list ):
AirPark.1.6.2.0_11242017
BetterBurnTime-1.6.1
Community_Resource_Pack-0.8.0.0
CTI.0.1.9
Decoupler_Shroud-0.3.1
DockRotate-1.3.1.5
EasyVesselSwitch_v1.5
EnvironmentalVisualEnhancements-1.2.2.1
IndicatorLights-1.2.12
KAS_v0.6.3
KerbalAlarmClock_3.8.5.0
KerbalEngineer-1.1.3.0
KerbalJointReinforcement_v3.3.3
KIS_v1.9
Malemute_0.4.0.0
ModuleManager.3.0.1.dll
NavBallDockingAlignmentIndicatorCE-1.0.3
Near_Future_Electrical-0.9.8
Near_Future_Solar-0.8.8
OSEWorkshop-1.2.3
ParaSciEVEPack120
Portrait_Stats-15.1
PreciseManeuver
SCANsat-v18.4
SimpleAdjustableFairings-KWRocketry-v1.0.1
SimpleLogistics-2.0.2
Snacks_1_8_7
Stockalike_Station_Parts_Expansion_Redux-1.0.2
Trajectories-v2.0.0
TransferWindowPlanner_1.6.2.0
UbioWeldContinued-2.5.2
USITools_0.10.1.0
VertVel132

**Comment by PiezPiedPy** [comment]
The NewGui has window persistence even after a restart. I suggest deleting the Trajectories folder from GameData and reinstalling to see if that fixes the problem.

**Comment by Brusura** [comment]
Problem fixed by reinstalling
