### ISSUE TITLE
Target longitude "drifts" (value decreases) when above 100km 

### ISSUE THREAD

**Issue by dlrk2** [neuoy/KSPTrajectories#140]
When a target on the surface of a body is selected and the active craft is above 100k,, the longitude of the target drifts, numerically decreasing. This occurs regardless of how the target is selected. This issue can easily be reproduced by placing a craft in orbit around apparently any body, and selecting a target on the surface, such as KSC (or any other coordinate) , and observing the continual decrease in the longitude value.

The drift ceases when the craft is below 100km. I tested this on Kerbin, Mun, and Minmus.

No mods were installed in this test aside from Trajectories, MechJeb, and HyperEdit

**Comment by fat-lobyte** [comment]
Trajectories  2.0.0 with KSP 1.3.1?

**Comment by dlrk2** [comment]
Ah, I knew I forgot something! Yep

**Comment by PiezPiedPy** [comment]
I'll have a look at this when I have a go at fixing issue #136
I've got a feeling it is due to Unity not using doubles when transforming from World Space coordinates to Local Space coordinates.

**Comment by dlrk2** [comment]
Alright. Btw, if a 1.3.1 release could be included with this fix, it would be awesome (:

**Comment by PiezPiedPy** [comment]
Not promising anything but @Kobymaru suggested not so long ago that we keep a branch active for building 1.3.1 releases.
Probably now is a good time to start one before we get to far into 1.4.1

**Comment by fat-lobyte** [comment]
> Not promising anything but @kobymaru suggested not so long ago that we keep a branch active for building 1.3.1 releases.

No I actually meant 1.2.2 ;) But now that RSS and Principia already are, and RP-0 and RO are getting updated to 1.3.1, we might as well skip the 1.2.2 "oldstable" version and skip to 1.3.1. It will probably be less work because we can have a smaller diff with the NewGUI.

**Comment by fat-lobyte** [comment]
@dlrk2 Could you check out what happens when you disable "Orbital Drift Compensation" in the General Tab of the Settings Menu?

**Comment by fat-lobyte** [comment]
It seems that our original Author @neuoy might have run into this problem back in the day:

https://forum.kerbalspaceprogram.com/index.php?/topic/146651-vessel-moving-slower-than-its-velocity-under-100km/

**Comment by dlrk2** [comment]
@fat-lobyte 

I just tested on the same save as before, it makes no difference. Hopefully it didn't break any theories (:

**Comment by PiezPiedPy** [comment]
Just had a thought, maybe a bit of a cheat and hacky workaround but if we keep re-setting the target every few frames when above 100km the drift might decide to go away.
In the mean time users could just keep pushing the set waypoint button as fast as possible just like in Daley Thompson's Decathlon. 😜

**Comment by dlrk2** [comment]
I've tried tested this a bunch of times, and for me at least, the bug definitely occurs at 100km, not 120

**Comment by fat-lobyte** [comment]
I think I've found the issue.

In MapGui.cs, we set the target by getting a "World position", for example like this:

    Trajectory.Target.Set(body, body.GetWorldSurfacePosition(-0.04860002, -74.72425635, 2.0) - body.position);

This call stores the World position in the Target object. This is fine for anything below 100 km because the reference frame rotates with Kerbin. Above 100 km, this isn't true anymore, and the reference frame becomes inertial.

That means that whichever point we targeted will stay in the same place in world coordinates - but not relative to the surface anymore.

In my opinion, the fix is to change The Trajectories.Target object to store longitude/latitude values, and convert when reading to/writing from these coordinates.

**Comment by PiezPiedPy** [comment]
@dlrk2 Did the fix above work for you ?

**Comment by dlrk2** [comment]
Sort of/mostly. The longitude fluctuates from -074.629698 to -0.74629724. Obviously, it's not a major distinction, so perhaps just truncate the lat and lon?

**Comment by fat-lobyte** [comment]
> -074.629698 to -0.74629724.

That's well within the expected margin, we can't be infinitely precise. Also, the drift was constant and not fluctuating. Therefor closing this issue as fixed.
