### ISSUE TITLE
Feature Request: Link navball dot to maneuver node, allowing it to be automatically tracked, provide separate GUI display of navball dot/square

### ISSUE THREAD

**Issue by dlrk2** [neuoy/KSPTrajectories#142]
Hey, got a couple suggestions RE the navball dot and square display. It's extremely useful, and a couple changes/extensions would make it even more so:

Provide an option to link the dot to the maneuver node, like how Mechjeb does with landing and ascent guidance, allowing it to be automatically tracked.

Provide a separate GUI window for the information provided by the dot and square, like an ILS type display, with the north/south deviation plotted on an X axis and the east/west deviation on a Y axis.

Thanks for considering!

**Comment by PiezPiedPy** [comment]
I think this is too far from the scope of what Trajectories does, this would be better of as its own mod, also I have not got the time to be writing this much code.
