### ISSUE TITLE
[Implemented] Fixed part of the Japanese translation

### ISSUE THREAD

**Issue by UresiiZo** [neuoy/KSPTrajectories#144]
I tried to correct Japanese. It is difficult to properly translate "Impact". I can tell what "Fixed Body" is also showing, but I can not idea proper words.
What kind of information is this "impact" and "Fixed Body" displayed?

        #autoLOC_Trajectories_Title = 軌道
        #autoLOC_Trajectories_AppButtonTooltip = 右クリックで軌道ウィンドウを切り替えます
        #autoLOC_Trajectories_ConicsErr = パッチされた円錐が利用できないため、軌道を表示することはできません。追跡ステーションの施設を更新してください。
        #autoLOC_Trajectories_Target = 対象
        #autoLOC_Trajectories_Descent = 降下
        #autoLOC_Trajectories_ShowTrajectory = 軌道を表示
        #autoLOC_Trajectories_InFlight = 飛行中
        #autoLOC_Trajectories_FixedBody = 固定式
        #autoLOC_Trajectories_Complete = コンプリート
        #autoLOC_Trajectories_MaxGforce = 最大減速重力加速度
        #autoLOC_Trajectories_ImpactVelocity = 影響速度
        #autoLOC_Trajectories_ImpactPosition = 影響位置
        #autoLOC_Trajectories_ImpactTime = 影響を受けるまでの時間
        #autoLOC_Trajectories_UseBlizzyToolbar = Blizzyのツールバーを使用する - 再起動後に有効
        #autoLOC_Trajectories_DefaultDescent = 機体の打ち上げ時の初期設定を逆行にする
        #autoLOC_Trajectories_UseCache = キャッシュを使用
        #autoLOC_Trajectories_UseCacheNote = キャッシュを無効にすると軌道がより正確になりますが、計算に時間がかかります。 CPUが負荷を処理できない場合は、無効化をお勧めしません。
        #autoLOC_Trajectories_AutoUpdate = 自動更新
        #autoLOC_Trajectories_AutoUpdateNote = 空力モデルを自動的に更新します。例えば、パーツが分離されている場合、モデルを更新する必要があります。これは軌道更新の干渉を受けません。
        #autoLOC_Trajectories_Update = 更新
        #autoLOC_Trajectories_MaxPatches = 最大パッチ
        #autoLOC_Trajectories_MaxFramesPatch = 最大フレーム/パッチ
        #autoLOC_Trajectories_IntegrationStep = 統合ステップ
        #autoLOC_Trajectories_CalcTime = 計算時間
        #autoLOC_Trajectories_Errors =エラー
        #autoLOC_Trajectories_AeroModel =空力モデル
        #autoLOC_Trajectories_Stock =ストック
        #autoLOC_Trajectories_NotLoaded =ロードされていません
        #autoLOC_Trajectories_NewGui = 新しいGUI
        #autoLOC_Trajectories_Entry = 突入
        #autoLOC_Trajectories_EntryDesc =大気圏突入時の宇宙船の角度
        #autoLOC_Trajectories_High = 高空
        #autoLOC_Trajectories_HighDesc =大気高度50％の宇宙船の角度
        #autoLOC_Trajectories_Low =低空
        #autoLOC_Trajectories_LowDesc =大気高度25％の宇宙船の角度
        #autoLOC_Trajectories_Ground =地上
        #autoLOC_Trajectories_GroundDesc =地上の宇宙船の角度
        #autoLOC_Trajectories_TargetBody =目標対象物
        #autoLOC_Trajectories_TargetPosition =目標位置
        #autoLOC_Trajectories_TargetDistance =目標距離
        #autoLOC_Trajectories_TargetSelect =目標を選択
        #autoLOC_Trajectories_TargetImpact =現在のインパクト
        #autoLOC_Trajectories_TargetVessel =目標の機体
        #autoLOC_Trajectories_TargetWaypoint =有効な地点
        #autoLOC_Trajectories_TargetHelp =目標の緯度と経度をコンマ区切りで入力
        #autoLOC_Trajectories_TargetManual =目標を手動設定
        #autoLOC_Trajectories_TargetClear =目標を削除
        #autoLOC_Trajectories_TargetingImpact =現在のインパクト位置をターゲットとする軌道
        #autoLOC_Trajectories_TargetingKSC = KSCを目標とする軌道
        #autoLOC_Trajectories_TargetingVessel =機体を目標とする軌道 '<< 1 >>'
        #autoLOC_Trajectories_TargetingWaypoint =地点を目標とする軌道 '<< 1 >>'
        #autoLOC_Trajectories_TargetingManual =手動目標位置を目標とする軌道
        #autoLOC_Trajectories_Lat = 緯度
        #autoLOC_Trajectories_Long =経度
        #autoLOC_Trajectories_Vert = 垂直
        #autoLOC_Trajectories_Hori = 水平
        #autoLOC_Trajectories_ms = m/s
        #autoLOC_Trajectories_km = km

**Comment by PiezPiedPy** [comment]
@UresiiZo The mod displays trajectory predictions, accounting for atmospheric drag and lift.

***'Impact'*** means the action of one object coming forcibly into contact with another (i.e. a car crashing into another car).
***'Impact position'*** is the predicted location on the ground or sea that the craft will crash or land (basically its final destination).
***'Impact velocity'*** is the speed in meters/second that the craft will be traveling when it crashes or lands.

In ***'Fixed Body'*** mode, the trajectory is displayed relatively to the body frame following the body rotation (body being the closet planet/moon/sun to the predicted trajectory).
In the Manual it states.
### Fixed Body mode 
Use this toggle to switch between the regular mode (similar to stock KSP orbits), or Fixed Body mode. In Fixed Body mode, the trajectory is displayed relatively to the body frame, following the body rotation. This mode makes sense for atmospheric or low terrain fly-by, and also to adjust a geostationary orbit.

Hope this helps you to understand the wording better 😉

**Comment by UresiiZo** [comment]
Thank you for detailed explanation.
Another one, What is "complete"?

Japanese will improve a little more.

**Comment by PiezPiedPy** [comment]
@UresiiZo
***'Stock'*** in this context means standard (i.e. original rather than modified.)
***'Stock'*** is displayed when Trajectories is using the standard/original KSP physics math model for aerodynamic calculations. If the mod 'Ferram Aerospace Research (FAR)' is installed then Trajectories will use the 'FAR' mod for calculations and display ***'FAR'*** instead of the word ***'Stock'*** .
e.g. **Aerodynamic model: Stock**
or **Aerodynamic model: FAR**

***'Complete'*** in this context means to make something full or entire.
The ***'Complete'*** button is used to toggle display of all of the trajectory, including the parts where it matches the standard KSP orbit.
In the manual it says:
Click "Complete" to toggle display of the complete trajectory (including parts where it is superimposed with the stock KSP trajectory).

**Comment by PiezPiedPy** [comment]
@UresiiZo 
Yes the Title is also in Japanese, configured with this line.
`#autoLOC_Trajectories_Title = 軌道`

So the Trajectories title on the Gui will read as:
### 軌道-v2.1.0

If you think it will be better for your language to display the Title as **'Trajectories-v2.1.0'** then change the line to:
`#autoLOC_Trajectories_Title = Trajectories`

**Comment by UresiiZo** [comment]
Translation is over.
I think that the title should remain in English.
Because the original goodness may be destroyed, the title is good as it is.

If the title is also in Japanese, I think that "軌道表示" is appropriate.

In the future, if there is a change in the word, please let me fix the translation again.
I'm also looking forward to future updates.


        #autoLOC_Trajectories_Title = Trajectories
        #autoLOC_Trajectories_AppButtonTooltip = 右クリックで軌道ウィンドウを切り替えます
        #autoLOC_Trajectories_ConicsErr = パッチされた円錐が利用できないため、軌道を表示することはできません。追跡ステーションの施設を更新してください。
        #autoLOC_Trajectories_Target = 対象
        #autoLOC_Trajectories_Descent = 降下
        #autoLOC_Trajectories_ShowTrajectory = 軌道を表示
        #autoLOC_Trajectories_InFlight = 飛行中
        #autoLOC_Trajectories_FixedBody = 相対
        #autoLOC_Trajectories_Complete = 一致
        #autoLOC_Trajectories_MaxGforce = 最大減速重力加速度
        #autoLOC_Trajectories_ImpactVelocity = 衝突速度
        #autoLOC_Trajectories_ImpactPosition = 衝突位置
        #autoLOC_Trajectories_ImpactTime = 衝突するまでの時間
        #autoLOC_Trajectories_UseBlizzyToolbar = Blizzyのツールバーを使用する - 再起動後に有効
        #autoLOC_Trajectories_DefaultDescent = 機体の打ち上げ時の初期設定を逆行にする
        #autoLOC_Trajectories_UseCache = キャッシュを使用
        #autoLOC_Trajectories_UseCacheNote = キャッシュを無効にすると軌道がより正確になりますが、計算に時間がかかります。 CPUが負荷を処理できない場合は、無効化をお勧めしません。
        #autoLOC_Trajectories_AutoUpdate = 自動更新
        #autoLOC_Trajectories_AutoUpdateNote = 空力モデルを自動的に更新します。例えば、パーツが分離されている場合、モデルを更新する必要があります。これは軌道更新の干渉を受けません。
        #autoLOC_Trajectories_Update = 更新
        #autoLOC_Trajectories_MaxPatches = 最大パッチ
        #autoLOC_Trajectories_MaxFramesPatch = 最大フレーム/パッチ
        #autoLOC_Trajectories_IntegrationStep = 統合ステップ
        #autoLOC_Trajectories_CalcTime = 計算時間
        #autoLOC_Trajectories_Errors =エラー
        #autoLOC_Trajectories_AeroModel =空力モデル
        #autoLOC_Trajectories_Stock =ストック
        #autoLOC_Trajectories_NotLoaded =ロードされていません
        #autoLOC_Trajectories_NewGui = 新しいGUI
        #autoLOC_Trajectories_Entry = 突入
        #autoLOC_Trajectories_EntryDesc =大気圏突入時の宇宙船の角度
        #autoLOC_Trajectories_High = 高空
        #autoLOC_Trajectories_HighDesc =大気高度50％の宇宙船の角度
        #autoLOC_Trajectories_Low =低空
        #autoLOC_Trajectories_LowDesc =大気高度25％の宇宙船の角度
        #autoLOC_Trajectories_Ground =地上
        #autoLOC_Trajectories_GroundDesc =地上の宇宙船の角度
        #autoLOC_Trajectories_TargetBody =目標対象物
        #autoLOC_Trajectories_TargetPosition =目標位置
        #autoLOC_Trajectories_TargetDistance =目標距離
        #autoLOC_Trajectories_TargetSelect =目標を選択
        #autoLOC_Trajectories_TargetImpact =現在の衝突地点
        #autoLOC_Trajectories_TargetVessel =目標の機体
        #autoLOC_Trajectories_TargetWaypoint =有効な地点
        #autoLOC_Trajectories_TargetHelp =目標の緯度と経度をコンマ区切りで入力
        #autoLOC_Trajectories_TargetManual =目標を手動設定
        #autoLOC_Trajectories_TargetClear =目標を削除
        #autoLOC_Trajectories_TargetingImpact =現在の衝突位置を目標とする軌道
        #autoLOC_Trajectories_TargetingKSC = KSCを目標とする軌道
        #autoLOC_Trajectories_TargetingVessel =機体を目標とする軌道 '<< 1 >>'
        #autoLOC_Trajectories_TargetingWaypoint =地点を目標とする軌道 '<< 1 >>'
        #autoLOC_Trajectories_TargetingManual =手動設定を目標とする軌道
        #autoLOC_Trajectories_Lat = 緯度
        #autoLOC_Trajectories_Long =経度
        #autoLOC_Trajectories_Vert = 垂直
        #autoLOC_Trajectories_Hori = 水平
        #autoLOC_Trajectories_ms = m/s
        #autoLOC_Trajectories_km = km

**Comment by PiezPiedPy** [comment]
@UresiiZo 
Thanks again for this work and your welcome to make any future changes 😎
I'll include your changes in a commit and make sure to give you credit in the Changelog.

**Comment by PiezPiedPy** [comment]
commits are in, so closing
