### ISSUE TITLE
french localization

### ISSUE THREAD

**Issue by d-faure** [neuoy/KSPTrajectories#147]
Here's some suggestions for the french translation
``````
#autoLOC_Trajectories_MaxGforce = Forcer G décélération maximale
#autoLOC_Trajectories_IntegrationStep = Pas d'intégration
#autoLOC_Trajectories_NewGui = Nouvelle IHM
#autoLOC_Trajectories_TargetVessel = Vaisseau ciblé
#autoLOC_Trajectories_TargetWaypoint = Point de passage actif
#autoLOC_Trajectories_TargetingVessel = Trajectoires ciblant le vaisseau << 1 >>
#autoLOC_Trajectories_TargetingWaypoint = Trajectoires ciblant le point de passage '<< 1 >>

**Comment by neuoy** [comment]
I'd say MaxGforce = "force g maximale" (without "r")

**Comment by neuoy** [comment]
By the way, in what languages is KSP translated now? I did not remember it was translated in french?

**Comment by d-faure** [comment]
Well done, that was a typo. There's a french patch for v1.4.1, but I can't tell too much about it since I'm used to play the english version.

**Comment by neuoy** [comment]
Ok, cool :) That's great news about the french version, I might try that out some day, thanks for the info.

**Comment by PiezPiedPy** [comment]
@d-faure Thanks, I'll update the Localization with your fixes :wink:
@neuoy Languages currently supported in KSP v1.4.1 are English, Spanish, Russian, Simplified-Chinese, Japanese, German, French, Italian and Portuguese-Brazilian.

**Comment by PiezPiedPy** [comment]
Commit https://github.com/neuoy/KSPTrajectories/commit/78251914f286058c6bba5bd409cd8e1cf7c6e734 is done so closing
