### ISSUE TITLE
Trajectories is not showing up in the toolbar, or doing anything really

### ISSUE THREAD

**Issue by ExoFage** [neuoy/KSPTrajectories#149]
It acts as if it's not even installed. 
I am using the most recent versions of both Trajectories and KSP (64-bit)
Stock aerodynamics (cubes)
I have a very extensive mod list, and couldn't single it down to even a few mods. Maybe I'm just not good at reading the log file.

Sorry for any trouble ahead of time, I tried to include as much info as I had but... i don't have much

Here is my log file and Mod List:
[My Stuff.zip](https://github.com/neuoy/KSPTrajectories/files/1948877/My.Stuff.zip)

**Comment by PiezPiedPy** [comment]
I noticed you have Blizzy Toolbar installed, have you tried the configure buttons option in the toolbar when in flight, is there a trajectories icon in there ?

Also have you tried with all mods removed except Trajectories ?

If Trajectories does not work when it is the only mod installed then all I can suggest is reinstalling KSP and trying again. make sure to back up your save games.

Also the log file we need for debugging is in your `C:\Users\[YourUserName]\AppData\LocalLow\Squad\Kerbal Space Program` folder.

Here is some info that will help with bug searching https://github.com/neuoy/KSPTrajectories/blob/master/CONTRIBUTING.md#removing-mods-for-debugging

**Comment by PiezPiedPy** [comment]
Closed due to lack of informmation
