### ISSUE TITLE
After showing UI with right-click and closing, then ALT-TABBING out of KSP the UI is not opening anymore

### ISSUE THREAD

**Issue by Gordon-Dry** [neuoy/KSPTrajectories#154]
I just ALT-TABBED out of KSP and then back in, now I can't open the Trajectories UI anymore.
It's also not "hidden" in the F2-toggled screen without UI (like it happens with ARP sometimes).

Using v2.2.1

There is no issue thrown in the log ...

**Comment by PiezPiedPy** [comment]
Trust you to break it 😛

**Comment by Gordon-Dry** [comment]
After a scene change aka. a new vessel launched the issue was gone in the same game session.
Just as a reminder.

**Comment by fat-lobyte** [comment]
I can't reproduce this, sorry.
