### ISSUE TITLE
Low FPS when used with Sigma Dimensions

### ISSUE THREAD

**Issue by Gordon-Dry** [neuoy/KSPTrajectories#156]
see
https://github.com/Sigma88/Sigma-Dimensions/issues/72#issuecomment-436282111

**Comment by PiezPiedPy** [comment]
Interesting

**Comment by fat-lobyte** [comment]
> see Sigma88/Sigma-Dimensions#72 (comment)

I don't "see" sufficient info to debug this in that comment,  but I do "see" that the problem does not exist anymore.

Feel free to come back with a better issue report, I suggest reading our section on [how to report bugs](https://github.com/neuoy/KSPTrajectories/blob/master/CONTRIBUTING.md#how-to-report-bugs) [1]

[1] https://github.com/neuoy/KSPTrajectories/blob/master/CONTRIBUTING.md#how-to-report-bugs
