### ISSUE TITLE
Cache provides no performance gain and is extremely inaccurate after warp (FAR)

### ISSUE THREAD

**Issue by dlrk2** [neuoy/KSPTrajectories#160]
I don't know if this issue exists only with FAR, but when cache is enabled, my predictions are wildly inaccurate. There doesn't seem to be a performance gain either, so is cache really needed?

**Comment by fat-lobyte** [comment]
> I don't know if this issue exists only with FAR

FAR support is broken for now. Predictions will be very inaccurate either way.

> but when cache is enabled, my predictions are wildly inaccurate.

Flat trajectory?

> There doesn't seem to be a performance gain either, so is cache really needed?

It used to be needed, but the newer integrator raised precision for not too much performance loss. We will leave it in for now, but it should be disabled by default.

**Comment by dlrk2** [comment]
>FAR support is broken for now. Predictions will be very inaccurate either way.

It really isn't though, I can land right on top of KSC, just need to maneuver +/- 1 degree to correct. Not unrealistic, and pretty easy.

**Comment by fat-lobyte** [comment]
Really? That would be interesting. Could you post your versions of KSP, Trajectories and FAR? Also, what kind of craft are you using?

**Comment by fat-lobyte** [comment]
Closing due to lack of response
