### ISSUE TITLE
Decerelation G-Force inaccurate with FAR

### ISSUE THREAD

**Issue by dlrk2** [neuoy/KSPTrajectories#161]
I'm not sure if this only occurs with FAR or always, but the deceleration g-force predicted doesn't ever seem to be more than 0.01

**Comment by fat-lobyte** [comment]
FAR support is pretty broken at this point. I tried digging into it once, but I believe the FAR API just sent the wrong value (or we weren't using it right?).

That's compounded by ferram4 being MIA and FAR being basically unmaintained.
