### ISSUE TITLE
Bootstrapper really necessary?

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#163]
@PiezPiedPy 

I see that you added a lot of code and scripts and logic in order to select the proper build for the right KSP version.
I am wondering: is this really necessary?

Generally, a DLL compiled for KSP 1.3.1 should still work in KSP 1.7.1, provided the API didn't change. If the API *did* in fact change, there is a neat trick to work around it using introspection:

```csharp
if (Versioning.version_minor > 3)
{
    // The following field didn't exist pre KSP v1.4
    var fInf = v.GetType().GetField("skipGroundPositioning");
    fInf.SetValue(v, false);
}
```

Honestly, I would much, much prefer building one single DLL for multiple versions without any kind of shimming and bootstrapping, since that complicates the build/packaging process and as can be seen with the latest update also locks people out using it with a KSP version we didn't anticipate. What do you say?

**Comment by PiezPiedPy** [comment]
I have to agree with you, using a single dll would be preferential. I got the idea of the bootstrap from Kerbalism where we though it would help users with installation by only having a single release for all versions.

As far as I know 1.3 used an older version of Unity than 1.4 to 1.7 which meant we had to compile against another version of unity resulting in separate Trajectories.dll's. Looks like we have the same again with 1.8. I'm not sure if reflection would work in this scenario, I could be totally wrong though.

**Comment by PiezPiedPy** [comment]
@fat-lobyte Sorry I didn't reply earlier I've been buried under work and totally forgot about KSP and fun lol :\

**Comment by fat-lobyte** [comment]
@PiezPiedPy Have you given this some thought? I think the whole bootstrapper/loading stuff makes things very complicated, and it automatically breaks the Plugin for newer KSP versions until we manually fix it (see #175).

I wonder if we should just re-target it to a newer minimum version (maybe 1.8.1), do some testing to make sure it works. If there is something in the API that changed, we can use Reflection to work around it.

**Comment by PiezPiedPy** [comment]
I have no problem with dropping backport support, it is a pain having to run multiple builds and testing, we could move the current master branch to a new one and call it backport so if anyone wants to build a backport they can. If anyone wants to keep backports up to date then they can pass in a PR or commit to that branch.

**Comment by PiezPiedPy** [comment]
@fat-lobyte Using reflection has performance penalties ideally we should stay away from it unless its use is absolutely necessary. I would prefer to build against the 1.8+ libraries and loose the older version support. Also the 1.8 builds may run fine on 1.7 as there are no code changes in Trajectories between 1.7 and 1.8, depends if the 1.8 Trajectories.dll will link to 1.7 dll's when KSP loads it.

**Comment by PiezPiedPy** [comment]
Here is some profiling of the Get/Set methods of a Property. Taken from [https://mattwarren.org/2016/12/14/Why-is-Reflection-slow/](url)

**Reading a Property (‘Get’)**
Method | Mean | StdErr | Scaled | Bytes Allocated/Op
-- | -- | -- | -- | --
GetViaProperty | 0.2159 ns | 0.0047 ns | 1.00 | 0.00
GetViaDelegate | 1.8903 ns | 0.0082 ns | 8.82 | 0.00
GetViaILEmit | 2.9236 ns | 0.0067 ns | 13.64 | 0.00
GetViaCompiledExpressionTrees | 12.3623 ns | 0.0200 ns | 57.65 | 0.00
GetViaFastMember | 35.9199 ns | 0.0528 ns | 167.52 | 0.00
GetViaReflectionWithCaching | 125.3878 ns | 0.2017 ns | 584.78 | 0.00
GetViaReflection | 197.9258 ns | 0.2704 ns | 923.08 | 0.01
GetViaDelegateDynamicInvoke | 842.9131 ns | 1.2649 ns | 3,931.17 | 419.04

**Writing a Property (‘Set’)**
Method | Mean | StdErr | Scaled | Bytes Allocated/Op
-- | -- | -- | -- | --
SetViaProperty | 1.4043 ns | 0.0200 ns | 6.55 | 0.00
SetViaDelegate | 2.8215 ns | 0.0078 ns | 13.16 | 0.00
SetViaILEmit | 2.8226 ns | 0.0061 ns | 13.16 | 0.00
SetViaCompiledExpressionTrees | 10.7329 ns | 0.0221 ns | 50.06 | 0.00
SetViaFastMember | 36.6210 ns | 0.0393 ns | 170.79 | 0.00
SetViaReflectionWithCaching | 214.4321 ns | 0.3122 ns | 1,000.07 | 98.49
SetViaReflection | 287.1039 ns | 0.3288 ns | 1,338.99 | 115.63
SetViaDelegateDynamicInvoke | 922.4618 ns | 2.9192 ns | 4,302.17 | 390.99

As you can see using reflection to call a properties Get/Set takes approx 500 times longer 😱

**Comment by fat-lobyte** [comment]
> As you can see using reflection to call a properties Get/Set takes approx 500 times longer 😱

Ouch. Well, fair enough then.

> we could move the current master branch to a new one and call it backport so if anyone wants to build a backport they can. If anyone wants to keep backports up to date then they can pass in a PR or commit to that branch.

Sounds great!
