### ISSUE TITLE
[Solved] Pausing (esc) -> GUI disappears, toolbar button becomes unresponsive.

### ISSUE THREAD

**Issue by tofof** [neuoy/KSPTrajectories#164]
## Observed behavior
While the Trajectories GUI is open, hitting esc to pause the game causes the GUI to disappear and the toolbar button to become unresponsive.

## Expected behavior
Opening esc menu has no effect on Trajectories GUI or button

**Comment by zdrake314** [comment]
I am experiencing this issue as well.

**Comment by mwerle** [comment]
Some investigation shows that if the game is resumed by clicking the dialog button on the pause menu, the Trajectories Window is not destroyed.

But if unpausing the game by pressing ESCAPE again, the dialog's OnPopupDialogDestroy() is called.

There's no need to reallocate all the items as per the pull request #165 but it is necessary to recreate the actual PopupDialog.

**Comment by PiezPiedPy** [comment]
This should be fixed in the next release thanks to @whale2 and @mwerle 😎

**Comment by PiezPiedPy** [comment]
Fixed ;)
