### ISSUE TITLE
Question - any update on KSP 1.8.x support?

### ISSUE THREAD

**Issue by marcusdb** [neuoy/KSPTrajectories#167]

**Comment by PiezPiedPy** [comment]
I'm going to look into it over this weekend.

**Comment by Gordon-Dry** [comment]
Actually I'm using Trajectories in KSP 1.8.1:
https://github.com/Devoblue/KSPTrajectories/tree/ksp-1.8

It works, afaik. 
I don't know if the code is optimal, though.

**Comment by PiezPiedPy** [comment]
I've made changes to support 1.8.x seems to be ok just a few minor quirks such as the in-flight target is sometimes missing.

So going to hold off on release and see if someone can fix it 😞

**Comment by marcusdb** [comment]
Fair enough, thank you for looking into this!

**Comment by PiezPiedPy** [comment]
Releasing shortly 😉
