### ISSUE TITLE
[Feature Request] Predict trajectory for a specified stage

### ISSUE THREAD

**Issue by mwerle** [neuoy/KSPTrajectories#169]
Currently, Trajectories only predicts the trajectory for the Craft as a whole.

In many cases, particularly when returning to Kerbin, Craft consist of a stage performing the deorbit burn, which is then staged, and a descent stage, which is unpowered.  The trajectory prediction is vastly different (obviously) before and after staging.

It would be great if the trajectory could be (optionally) calculated for the descent stage (might need to be selected by the user) instead of the entire current Craft, ideally taking into account the separation force as well.  
Or possibly have a prediction for the current Craft with a secondary prediction (in a different colour) for the next stage.

Several mods "break" Craft into individual stages for modelling (eg, KER, StageRecovery) so there should be plenty of sample code on how to do this. It should then be easy(*) to model each stage separately.

(*) Sorry, haven't looked at the source code for Trajectories yet. "Should be easy" is easy to say but I undestand that depending on the code architecture it may not be.

**Comment by Travia21** [comment]
As identified here [https://forum.kerbalspaceprogram.com/index.php?/topic/162324-131-172-trajectories-v223-2019-06-17-atmospheric-predictions/](Mod Forum Post), future stages can't be simulated.

**Comment by mwerle** [comment]
My apologies, did not read FAQ on the forum.  Perhaps duplicate the FAQ in the README?  I don't always read forum posts when working on code/github.

**Comment by PiezPiedPy** [comment]
@mwerle You have a point there 😉
