### ISSUE TITLE
There is Z-fighting between impact markers and the surface

### ISSUE THREAD

**Issue by mic-e** [neuoy/KSPTrajectories#17]
Z-fighting between a impact marker and the surface was noticed in the hilly terrain of Minmus.
Z-fighting between the two markers was noticed upon setting the current marker as the target (on Minmus).

I'm on Linux, with `nvidia`, if that matters.

**Comment by OzoneGrif** [comment]
I'm on Windows, nvidia, and this bug has been around for eons. It occurs on other planets as well (Minus, Mun, Bop, ...)

The solution would be to move the marker higher in the sky above the terrain.

**Comment by neuoy** [comment]
issue fixed for next release ; there was also problems with the impact position itself (when hitting a mountain on a grazing trajectory for example) which lead to an impact point that actually was underground
