### ISSUE TITLE
mod missing from toolbar

### ISSUE THREAD

**Issue by devontheyoutuber** [neuoy/KSPTrajectories#174]
im experincing a bunch of lag the way i usually fix this is disabling the cache but i cant find the mod in the tool bar

**Comment by PiezPiedPy** [comment]
Do you know that the icon only shows when in-flight ?
If there is no icon in-flight have you tried deleting the Trajectories folder and re-installing.
Or maybe a Blizzy toolbar settings problem if your using it.

**Comment by PiezPiedPy** [comment]
Closing not enough feedback, although this issue should be fixed with commit  https://github.com/neuoy/KSPTrajectories/commit/00080ba5c8fa5c18bfd8c861c3f1299dda2e6d8f
