### ISSUE TITLE
KSP 1.10.x compatibility

### ISSUE THREAD

**Issue by gabbonj** [neuoy/KSPTrajectories#175]
The mod is not supported for the latest version of  KSP.

**Comment by PiezPiedPy** [comment]
Give us a chance, it's only been out a day 🤣

**Comment by PiezPiedPy** [comment]
For a quick fix that may not work try renaming the file _**Trajectories19.bin**_ to **_Trajectories110.bin_**

**Comment by gabbonj** [comment]
It works, thank you!!!
