### ISSUE TITLE
Not using Kerbal Konstructs, KSC floats off the ground by 71 meters when using Sigma and 2.5x

### ISSUE THREAD

**Issue by SlainteMaith** [neuoy/KSPTrajectories#180]
This is fixed by editing 2.5xKSRSS.cfg and changing the offset.

`@Kopernicus:LAST[KSRSS]:NEEDS[SigDim,!KerbalKonstructs]
{
	@Body:HAS[@Template:HAS[#name[Kerbin]]]
	{
		@SpaceCenter
		{
			@repositionRadiusOffset = 585
			@radius = 6000
			@absoluteOffset = 460
		}
	}`

**Comment by SlainteMaith** [comment]
This is not for this mod.  I don't recall being drunk when I added this.  Huh.

**Comment by PiezPiedPy** [comment]
> This is not for this mod. I don't recall being drunk when I added this. Huh.

@SlainteMaith You where definitely on something 🤣
