### ISSUE TITLE
Mod is acting as if it isn't installed

### ISSUE THREAD

**Issue by kerbalguy** [neuoy/KSPTrajectories#183]
This started on 1.12 I believe. Not getting any of the mod's trajectory predictions and the Trajectories icon isn't appearing in the toolbar. I've tried reinstalling the mod as well as KSP. Any help would be appreciated. :)

[KSP.log](https://github.com/neuoy/KSPTrajectories/files/7067978/KSP.log)

Let me know if there's anything else I need to attach.

**Comment by PiezPiedPy** [comment]
@kerbalguy
 
You also have problems with MechJeb, Kronometer and TweakScale
[ERR 13:52:47.943] MechJeb caught a ReflectionTypeLoadException. Those DLL are not built for this KSP version:

[ERR 13:52:47.943] Kronometer 1.0.0.0 GameData\JNSQ\JNSQ_Plugins\Kronometer\Plugins\Kronometer.dll
System.TypeLoadException: VTable setup of type Kronometer.ClockFormatter failed
[ERR 14:15:22.954] Module TweakScale threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object

Trajectories threw this error
[ERR 15:57:06.616] Exception loading ScenarioModule Trajectories: System.TypeInitializationException: The type initializer for 'Trajectories.Settings' threw an exception. ---> 

which occurred while Trajectories was constructing its settings and called KSP.IO.PluginConfiguration.CreateForType, this error occurred inside KSP's code and thus I cannot help. 

Try removing these mods and see if it fixes the problem, obviously you have a mod conflict, have a read of the [CONTRIBUTING.md](https://github.com/neuoy/KSPTrajectories/blob/master/CONTRIBUTING.md) file specifically here [CONTRIBUTING.md#removing-mods-for-debugging](https://github.com/neuoy/KSPTrajectories/blob/master/CONTRIBUTING.md#removing-mods-for-debugging)

**Comment by kerbalguy** [comment]
> @kerbalguy
> 
> You also have problems with MechJeb, Kronometer and TweakScale
> [ERR 13:52:47.943] MechJeb caught a ReflectionTypeLoadException. Those DLL are not built for this KSP version:
> 
> [ERR 13:52:47.943] Kronometer 1.0.0.0 GameData\JNSQ\JNSQ_Plugins\Kronometer\Plugins\Kronometer.dll
> System.TypeLoadException: VTable setup of type Kronometer.ClockFormatter failed
> [ERR 14:15:22.954] Module TweakScale threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
> 
> Trajectories threw this error
> [ERR 15:57:06.616] Exception loading ScenarioModule Trajectories: System.TypeInitializationException: The type initializer for 'Trajectories.Settings' threw an exception. --->
> 
> which occurred while Trajectories was constructing its settings and called KSP.IO.PluginConfiguration.CreateForType, this error occurred inside KSP's code and thus I cannot help.
> 
> Try removing these mods and see if it fixes the problem, obviously you have a mod conflict, have a read of the [CONTRIBUTING.md](https://github.com/neuoy/KSPTrajectories/blob/master/CONTRIBUTING.md) file specifically here [CONTRIBUTING.md#removing-mods-for-debugging](https://github.com/neuoy/KSPTrajectories/blob/master/CONTRIBUTING.md#removing-mods-for-debugging)

**Comment by PiezPiedPy** [comment]
This happens a lot due to KSP bumming out of loading mods if one of them has an issue loading, mods already loaded before the offending mod will load and those after will fail.

I will put the call in a try block and catch the error and exit Trajectories gracefully with an on screen warning to the user.

**Comment by PiezPiedPy** [comment]
Done, hopefully the on screen message will help some people resolve their issues.
