### ISSUE TITLE
Divide by zero exception spam

### ISSUE THREAD

**Issue by sick13** [neuoy/KSPTrajectories#184]
This happened when i was doing some testing (not related to this mod) so i cheat my self into laythe orbit (was fixing some SVE clouds and stuff) then i reverted back to VAB made a simple rocket launched it and then the nullrefs started spamming,this does not happen when i launch a fresh game and i don't teleport to other planets as far as i can tell

PS.
i noticed that some lines in the config.xml have a setting set to zero,i might be related to a problem smoke screen mod was having
the "ZERO" in the settings was causing problems,maybe this is the case here also,just a thought

https://forum.kerbalspaceprogram.com/index.php?/topic/64987-18x-110x-smokescreen-2814-extended-fx-plugin-18-april-2020/&do=findComment&comment=3526423

[EXC 22:52:51.189] DivideByZeroException: Attempted to divide by zero.
	Trajectories.Trajectory+<AddPatch>d__48.MoveNext () (at <f3d07aa3ca24425db4dec3b56b8c6642>:0)
	Trajectories.Trajectory+<ComputeTrajectoryIncrement>d__39.MoveNext () (at <f3d07aa3ca24425db4dec3b56b8c6642>:0)
	Trajectories.Trajectory.ComputeTrajectory () (at <f3d07aa3ca24425db4dec3b56b8c6642>:0)
	Trajectories.Trajectory.Update () (at <f3d07aa3ca24425db4dec3b56b8c6642>:0)
	Trajectories.Trajectories.Update () (at <f3d07aa3ca24425db4dec3b56b8c6642>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

and so it goes until returning to VAB

**Comment by sick13** [comment]
thx for taking a look

**Comment by PiezPiedPy** [comment]
@sick13 I've tried to reproduce the exception but have had no luck, any you chance you could install this debug version and post your ksp.log when you encounter the bug.

[TrajectoriesDebug-v2.4.4.zip](https://github.com/neuoy/KSPTrajectories/files/8145073/TrajectoriesDebug-v2.4.4.zip)

**Comment by sick13** [comment]
Will do,tonight or tomorrow as i am not at home currently,will let you know what i find if anything
