### ISSUE TITLE
In-flight trajectory only shows the last path segment

### ISSUE THREAD

**Issue by Tuupertunut** [neuoy/KSPTrajectories#188]
**KSP version:** 1.12.1
**Trajectories version:** 2.4.3

**How to reproduce:**

1. Enable In-flight display from Trajectories.
2. Launch a craft to a suborbital trajectory.
3. Before entering space, zoom out from the craft and look at the shape of the in-flight trajectory.
4. Compare the trajectory to the one shown in map view.

**Expected behavior:**

The in-flight and map view trajectories should look the same.

**Actual behavior:**

If the trajectory goes through the atmosphere twice, the in-flight trajectory is a straight line to the beginning of the second path segment through the atmosphere. That second path segment seems to be correctly drawn.

![screenshot74](https://user-images.githubusercontent.com/1782631/166574727-db781c11-fa16-424a-bd45-552b6911d741.png)
Map view

![screenshot73](https://user-images.githubusercontent.com/1782631/166574706-c184b299-5527-49b8-96a4-92918c525637.png)
In-flight view

**Comment by PiezPiedPy** [comment]
@Tuupertunut This is currently correct behaviour, In-Flight only shows the last patch as it was only intended for showing trajectories close to the surface, i.e. landing on the roof of the VAB.
