### ISSUE TITLE
DRE Support

### ISSUE THREAD

**Issue by Starstrider42** [neuoy/KSPTrajectories#33]
To formalize (and second) a suggestion made in #18, it would be nice to be able to predict whether a given trajectory is survivable under DRE. Specific things I'd like to see:

* Peak temperature of the heat shield
    - whether any other parts will overheat would also be useful, especially for spaceplanes, but might be prohibitive for large vessels
* Amount of ablative used (or, at least, whether or not the shield will run out). Note that running out of ablative is not necessarily fatal, if it happens late enough, so any warning messages should be based on peak temperature predictions instead.
* Consistent use of custom DRE parameters (i.e., the contents of the `REENTRY_EFFECTS` configNode) and custom heat shields (like the RSS pack)

**Comment by neuoy** [comment]
This feature seems too much work, especially now that there is both stock heat and DRE, and I also think FAR modifies the stock heat system. As always, anyone is welcome to implement the feature, but I'm most probably not going to do it myself.
