### ISSUE TITLE
Draw landing zone ellipse

### ISSUE THREAD

**Issue by neuoy** [neuoy/KSPTrajectories#37]
Or any other method to indicate how reliable the impact position is. For example by performing multiple predictions with slighly varying starting conditions to see if the trajectory is affected by the chaos theory.

**Comment by Aquilux** [comment]
I gave this some thought and I feel like it may not be that hard to implement actually, and would only need a "Maximum AoA" input from the user (0-90 degrees from the velocity axis) The landing ellipse itself will be constrained by three points:

1. The first point is constrained by the maximum range achievable within the specified AoA range along the current heading. This specifies the ellipse's furthest extent. 

2. The second point is defined by the maximum deflection possible within the specified AoA and assuming that this deflection is applied entirely to diving towards the planet. This is the shortest trajectory to the ground and specifies the ellipse's closest extent.

3.  The last two points are maximum cross range. This trajectory is similar to a ballistic trajectory as no lift is being directed up or down. Instead, maximum deflection is being applied laterally along the flight path to give you the extent and position of the widest extent of your ellipse.

This implementation has two drawbacks. First it assumes that once traveling straight down the craft will no longer deflect its trajectory, and second it does not account for craft with high enough lift to change it's trajectory more than 90 degrees laterally. This can probably be solved by generating intermediate trajectories between each case and drawing a curve sequentially through all landing locations and filling the inner area of the resulting shape. I would think two extra points (1/3 - 2/3, and 2/3 - 1/3 comprises in force between each case). I imagine a craft with enough lift would distort the shape out of an ellipse and may not need any points involving maximum deflection down to draw it's potential range, but I'd wager it's simpler to area fill a complex shape than it is to decide when to change methods.



If this does get implemented, I'd like to request that a secondary window be made available to display the landing zone shape on a lat-long grid in relation to the target you can already specify when not in map view. Also I would be exceptionally grateful if a marker could be added to indicate where to point the nose for the proper L/D max AoA.

**Comment by fat-lobyte** [comment]
If somebody wants to implement this, please go right ahead. I currently have no plans to do it.
