### ISSUE TITLE
A question about descent profile, and a possible bug

### ISSUE THREAD

**Issue by KriPet** [neuoy/KSPTrajectories#44]
Hi there, great mod.

Question: The angle of attack, is that relative to the *surface* velocity vector, or the *orbit* velocity vector. I'm guessing the first, since this mod seems targeted at planes.

Possible bug: I think -180 and 180 degrees give the same landing prediction? Currently they don't (Not off by much though)

**Comment by neuoy** [comment]
Angle of attack is relative to the surface velocity (which is also the velocity relatively to the air mass, as there is no wind in KSP)

And I've fixed the -180° bug.
