### ISSUE TITLE
Trajectories 1.1.2 (fat-lobyte fork) needs update for FAR 0.14.6

### ISSUE THREAD

**Issue by rdeforest** [neuoy/KSPTrajectories#51]
*I don't know if it's kosher to post a bug report about a fork in the issues of the original project, but I didn't see a way to post it to the fat-lobyte fork. Also I believe this is the same issue mentioned on the forums and acknowledged today by baythan. I'm posting here to document the issue more methodically.*

Trajectories prediction does not match FAR's latest model.

Defect reproduction method: Put a rocket in an orbit with a high apoapsis (~3Mm) and periapsis of ~65km. As the rocket passes through the periapsis the predicted next apoapsis will fall. Before I adapted my strategies this resulted in me setting up aerobrake orbits which were predicted to have two orbits after the first aerobrake, but actually ended up descending completely in the first aerobrake.

If this is expected behavior a warning would help, but I can also understand if this kind of surprise is by design and a warning would defeat that, in which case feel free to close this as "no issue" or "won't fix" or whatever. :)

I'm including the useful portion of my 'ckan list' for completeness' sake (why yes, I do have a lot of memory, why do you ask? :).

```
- AmbientLightAdjustment 1.3.1.1
- AutoAsparagus v0.8
- AviationLights 3.7
- CommunityResourcePack 0.3.2
- DistantObject v1.5.1
- DistantObject-default v1.5.1
- EditorExtensions 2.5.1
- EnhancedNavBall 1.3.4
- EnvironmentalVisualEnhancements-Config-Default 7-4
- EnvironmentalVisualEnhancements-HR 7-4
- FerramAerospaceResearch v0.14.6
- HullcamVDS 0.33
- InFlightWaypoints 1.2.7
- KAS 0.4.10
- KerbalEngineerRedux 1.0.14.1
- KerbalWeatherSystems 0.5.3-alpha
- LandingHeight 1.3
- MechJeb2 2.4.2
- ModuleManager 2.5.9
- PlanetShine 0.2.2.1
- PlanetShine-Config-Default 0.2.2.1
- PortableScienceContainer 1.2.1
- ProceduralFairings v3.11
- RasterPropMonitor-Core v0.18.3
- SafeChute 1.6
- SAVE 0.9.17-387
- SCANsat 8.1
- ScienceAlert 1.8.4
- SmartStage v2.5.0
- StageRecovery 1.5.3
- StationScience 1.4
- TCShipInfo 0.3
- TextureReplacer 2.2
- Toolbar 1.7.8
- Trajectories 1.1.2
- TWR1 1.17c
- USITools 0.3.1
- VNG-Parachute 1.2
- VNG-Parachute-EVALoading 1.0
- VNG-Plugin 0.7.2
```

**Comment by neuoy** [comment]
It's not really a fork but a continuation, so I guess grouping the issues makes sense. However I'm not familiar enough with github to know if fat-lobyte (or anyone else) can edit/label/close the issues if he wants.

About the issue, I think having a very excentric orbit (high apoapsis) will make the whole thing a lot more sensitive (a few meters difference in the periapsis can make an aerobrake become an aerocapture). Also, I don't think predictions have ever been completely accurate with FAR (or NEAR), are you sure it's specifically related to recent modifications of FAR ?

**Comment by rdeforest** [comment]
I don't have any particular reason to blame FAR or running 64 bit. I suppose the amount of atmosphere I'm going to go through matters too and that oblique approaches (my favorite) naturally accumulate more error. I'll experiment some more. Is there an easy way for me to test whether Trajectories' calculations are within normal tolerances? Maybe something on the debug console?

Also thank you for this mod. For me it's second only to MechJeb for mods I wouldn't want to play without.

**Comment by rdeforest** [comment]
I didn't do rigorous testing, but based on your feedback and my further observations I don't think there actually is an issue, so I'm closing this. Thanks again for your work!

**Comment by neuoy** [comment]
Actually, it probably was a bug. Don't know if you've seen the pre-release on the forum thread, some issues with FAR have been solved (they were specific to FAR, it worked fine with NEAR). Some technical details are in the development thread as well. But still a good thing you closed this issue though.

**Comment by rdeforest** [comment]
Yeah, I wasn't following FAR development and I do a ckan update; ckan
upgrade --all headless every time I'm about to start KSP. I also never
tested with NEAR.

I'm always glad to hear I'm not as crazy as I think. Thanks for the follow
up.
