### ISSUE TITLE
Game slows to a crawl when "display trajectory" is turned on and the current craft is on an escape trajectory

### ISSUE THREAD

**Issue by attosecond** [neuoy/KSPTrajectories#55]
KSP x64 on linux. If "display trajectory" is turned on and the active vessel is on an escape trajectory, the game slows to a very slow crawl when in map view. Using most recent beta release of Trajectories.

**Comment by neuoy** [comment]
Do you still have this issue with the latest version (1.3.0), that wasn't released at the time you reported the bug ? I've fixed things about SoI changes.

**Comment by attosecond** [comment]
Looks like you cleared up this bug... thanks! I couldn't live without this mod!
