### ISSUE TITLE
Trajectories Breaks RemoteTech

### ISSUE THREAD

**Issue by Pharylon** [neuoy/KSPTrajectories#57]
Trajectories is causing the signal delay to break in RemoteTech.

**Comment by neuoy** [comment]
Can you elaborate a bit please? What is happening exactly (I don't see what you mean by "breaking the signal delay"), and why do you think it's related to Trajectories? Thanks.

**Comment by Pharylon** [comment]
Throttling engines and attitude control work with no signal delay (some things, like toggling SAS,  still respect it though). I know it's Trajectories because it happens when I have Trajectories installed and doesn't when it's not. :)

**Comment by neuoy** [comment]
OK, I'll check that when I find some time, but it looks really weird, I don't see what part of Trajectories could interfere with that.

**Comment by neuoy** [comment]
I've been able to reproduce the issue, as weird as it seems.

**Comment by neuoy** [comment]
OK, I've found the culprit. The auto-pilot system of Trajectories was registering a Vessel.OnFlyByWire callback, and this seems to break Remote Tech signal delay. So I've completely removed the auto-pilot feature (which was exprerimental and I never took the time to debug it properly anyway). This fixes the Remote Tech compatibility. The fix will be deployed in the next release.

**Comment by Pharylon** [comment]
Thanks!
