### ISSUE TITLE
Bug on escape trajectory

### ISSUE THREAD

**Issue by neuoy** [neuoy/KSPTrajectories#60]
Even if the orbit is not an orbit but an escape trajectory, it computes the trajectory after a full or multiple orbits (which is not going to happen), which can mislead players into thinking they'll get captured after an aerobrake, while they're actually going to exit the sphere of influence.

**Comment by fat-lobyte** [comment]
So basically, the trajectory is computed for the current SOI only regardless of possible SOI transitions?

**Comment by neuoy** [comment]
The problem was only for orbits computed after an aerobrake. The bug is fixed for next release. I've found the KSP method that computes encounters for an orbit that is not in the stock flight plan, so now the mod computes SoI changes (both when escaping current body, or entering another). This should make the mod much more useful for aerobrakes, even if the predicted result is often imprecise ; small corrective burns should do.
