### ISSUE TITLE
Increase number of trajectory calculations?

### ISSUE THREAD

**Issue by KellanHiggins** [neuoy/KSPTrajectories#63]
I was wondering the best way to modify the number of calculations made per second when calculating drag. I need a VERY long calculations to land on Mars in RSS. Not super concerned about performance.

I am guessing there is no way to compile this without installing Unity 4.2 and using it to create the standard mod. Must this be compiled to a DLL before being used in Unity?

I am very familiar with C# and Unity (created my own game) so doing this wouldn't be a problem. Only issue is I just want to change one variable in the program and don't want to spend a lot of time installing all this stuff.

**Comment by Kerbas-ad-astra** [comment]
You don't need to install Unity -- just get a C# development environment (I use MonoDevelop/Xamarin Studio), reference a couple of DLLs that come with KSP, and go to town.  More information: http://wiki.kerbalspaceprogram.com/wiki/Tutorial:Creating_your_first_module

**Comment by KellanHiggins** [comment]
Awesome! Thanks!
