### ISSUE TITLE
NullRefException in AutoPilot during loading screen causes excessive log writes and slows down startup

### ISSUE THREAD

**Issue by OlivierHamel** [neuoy/KSPTrajectories#68]
amd64, windows, ksp v1.1.2

Trajectories.AutoPilot is set to EveryScene which includes the loading screen. At that point in time accessing class FlightGlobals via AutoPilot's Update method triggers a NRE. (Not certain why a static class access would trigger this.)

Either way, fix is trivial: Add a empty catch block to suppress the exception. This prevents it from being logged every frame during startup and dramatically slowing it down due to disk access. (I've done this on my local copy.)

Addendum:
Do no proceed with this fix. There's some strange interaction where it causes engines to consume no fuel.

Addendum 2:
Wrong again. Apparently any changes I do and compile with still result in the abnormal behaviour... Odd. Pardon, can't test any fixes for you. The catch might work, but if it doesn't I suggest changing the autopilot code to simply request the activevessel directly instead of polling for it every frame.

Addendum 3:

Appears to be a repost of #66. Please close/ignore, pardon.

**Comment by neuoy** [comment]
The "fuel consumption issue" is actually a feature: when you compile in debug mode, infinite fuel cheat is enabled. You can disable in KSP debug menu (ALT + F12). I made this for easier testing with simple rockets that can go very fast into orbit. As for the NRE, it's fixed in version 1.6.2 :)
