### ISSUE TITLE
Compiler Error in API.cs with KSP-1.2

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#77]
Hi!

@PBscoots added a few functions to API.cs, one of them is the following:

```csharp
public static Vector3 getImpactVelocity()
{
	foreach (var patch in Trajectory.fetch.patches)
	{
		if (patch.impactVelocity != null)
			return patch.impactVelocity;
	}
	return null;
}
```

However, if I compile that, I get the following error:

`Cannot convert null to 'Vector3' because it is a non-nullable value type`

I'm not quite sure what null is supposed to symbolize, so I don't know how to properly fix that. But maybe @PBscoots should take a look?

**Comment by Baleine82** [comment]
Hi,

Null means that there is no value.

If Vector3 is not nullable, replace the return statement with "return new Vector3();" (Or check if there is something like Vector3.Zero you could use instead)

Le 15 octobre 2016 22:10:13 GMT+02:00, Alexander Korsunsky <notifications@github.com> a écrit :
>Hi!
>
>@PBscoots added a few functions to API.cs, one of them is the
>following:
>
>```csharp
>public static Vector3 getImpactVelocity()
>{
>	foreach (var patch in Trajectory.fetch.patches)
>	{
>		if (patch.impactVelocity != null)
>			return patch.impactVelocity;
>	}
>	return null;
>}
>```
>
>However, if I compile that, I get the following error:
>
>`Cannot convert null to 'Vector3' because it is a non-nullable value
>type`
>
>I'm not quite sure what null is supposed to symbolize, so I don't know
>how to properly fix that. But maybe @PBscoots should take a look?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/neuoy/KSPTrajectories/issues/77

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fat-lobyte** [comment]
> Null means that there is no value.

Thanks, I know what null is in general ;)
This function was introduced by PBscoots for kOS. I don't know what the sematics of this function are, if the vector has "no value" and what he expects from this function.
Simply constructing it with no parameters will cause it to be a vector of (0,0,0) - which could be a legal value.

**Comment by Baleine82** [comment]
In my opinion, the function means there is an impact in the trajectory.

If no patches with impact velocity are found, then there is a problem.
You may use two approaches to that.

1) Throw an exception, with whatever consequences this may have
2) Return a valid vector (0) and have some side effects in case it happens

**Comment by PBscoots** [comment]
So I treated it that way because of the similar way impact position seems to be handled in the API and in the Trajectories.cs file. I guess the difference being that the impact velocity does not have the "?" operator after Vector3 and impactposition does. I am not sure why this is as I would think that impact position and velocity would return the same thing as if it doesn't have an impact position it will have not have an impact velocity. It looks like if I just  put the same ? operator after vector3 it compiles. Do you guys think this is sufficient or should a "return new Vector3()" be done instead

**Comment by PBscoots** [comment]
@neuoy could you maybe comment on why in the trajectories.cs file impactposition is declared as a vector3? and impactvelocity is not?

**Comment by neuoy** [comment]
Sorry, I've not looked at this issue yet, but I'll take a look as soon as I can. Right now, I don't see a reason why impact velocity is not nullable, it probably should (both in Trajectory core, and in the API)
