### ISSUE TITLE
[Implemented] Make GUI attitude settings settable in the API

### ISSUE THREAD

**Issue by npyoung** [neuoy/KSPTrajectories#82]
This improvement is mainly inspired by kOS's [Trajectories Addon](https://github.com/KSP-KOS/KOS/pull/1603). Right now this addon only has access to the functions provided by the Trajectories API, which means a kOS user much manually tug around sliders in the Trajectories GUI before using the predictions. Exposing the attitude settings in the API would allow kOS users to programmatically set the planned attitude at each point in the descent, enabling complete automation, and maybe even better integration with other mods.

**Comment by fat-lobyte** [comment]
@npyoung Before I do some work on this, I wanted to ask: is there still interest in this?

Could you have a look at the file `Plugin/DescentProfile.cs` and tell me what you need exposed? 

I was thinking of a struct within Trajectories.API called "DescentProfileNode" which would be similar to Trajectories.DescentProfile.Node. Something like this:

```
struct DescentProfileNode {
            public double angle; // in radians
            public bool horizon; // if true, angle is relative to horizon, otherwise it's relative to velocity (i.e. angle of attack)
}
```

And in the API, there would be one function that takes four of these:

`void setDescentProfile(DescentProfileNode entryNode, DescentProfileNode highNode, DescentProfileNode lowNode, DescentProfileNode finalNode);`

Does this work for you?

Preferrably, could you (or some other kOS person) submit a Pull Request? That would be really condusive to exposing what you need.

**Comment by darkbushido** [comment]
I was just about to ask for this feature.

**Comment by akors** [comment]
> I was about to submit a request to be able to set pro/retro from KOS. I assume this would do the same thing?

Yes it would, but before doing anything I would like to have a little discussion with the KOS people who would implement it on the KOS side and the people who would use it in their scripts about what is actually needed and how to best design the API.

But unfortunately, @npyoung has since disappeared. Hence the "needinfo" label.

**Comment by fat-lobyte** [comment]
> I was about to submit a request to be able to set pro/retro from KOS. I assume this would do the same thing?

Yes it would, but before doing anything I would like to have a little discussion with the KOS people who would implement it on the KOS side and the people who would use it in their scripts about what is actually needed and how to best design the API.

But unfortunately, @npyoung has since disappeared. Hence the "needinfo" label.

**Comment by PiezPiedPy** [comment]
Just a heads up, I'm currently working on this 😉

**Comment by PiezPiedPy** [comment]
Added properties into the API `ProgradeEntry` and `RetrogradeEntry`

@darkbushido I've made a PR into kOS that will hopefully make it into the next release of kOS, I've added the suffixes `Prograde` and `Retrograde` and some others. See https://github.com/KSP-KOS/KOS/pull/2220

**Comment by PiezPiedPy** [comment]
Next additions have been mentioned here https://github.com/KSP-KOS/KOS/issues/2263
I'll get on it in the near future.

**Comment by PiezPiedPy** [comment]
New API methods where added for the Descent Profile for Trajectories v2.3.2 `ResetDescentProfile DescentProfileAngles DescentProfileModes`.

The next release of Trajectories being v2.4.0 will also have new API methods `GetTarget` and `ClearTarget`.

**Comment by PiezPiedPy** [comment]
Added an API method `DescentProfileGrades` to set individual descent profile nodes to pro/retrograde.

Closing as needed API methods are now implemented.
