### ISSUE TITLE
Incorrect prediction for simple crafts with Stock Aero

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#84]
Even with crafts as simple as a single Mk1-Command Pod, the impact precision is incorrect in Stock KSP (without FAR).

1. Load the following quicksave: [Mk1-Pod-Only.zip](https://github.com/neuoy/KSPTrajectories/files/741656/Mk1-Pod-Only.zip)
2. In the Debug menu under Cheats, enable infinite electricity for perfect attitude control.
3. Set The NavBall to the surface mode
4. Set The Pilot mode to Retrograde
5. Set the current impact to target
6. Timewarp to the atmosphere
7. Leave the craft be, and observe the distance to target

As you can observe, the impact point continously drifts away from the target. The actual impact ends up to be around 90 km away from the initially predicted point.

This is independent of

- Cache or No Cache
- Body Fixed or not
- Physics time acceleration

**Comment by skrelk** [comment]
I've mentioned this on the forum, but I figure it might be used for this to be posted here:

This issue does not occur if FAR is used

**Comment by fat-lobyte** [comment]
> This issue does not occur if FAR is used

Thanks, this is a problem with the calculation of stock forces. I should clarify that in the Title and text.

**Comment by Charon77** [comment]
I've played around with the cheat options, namely the aero (body lift), drag, temperature

Changing body lift multiplier (as with global lift multiplier in the aero section) doesn't seem to improve accuracy. Changing temperature parameter such as convection, radiation, and the sun options below it changes nothing as well

The main culprit seems to be in the drag section. I've tried checking the option to change all drag cubes to drag spheres, and got 55km within predicted impact site! (as opposed to 98km under normal circumstances)

So I believe something is wrong with the way drag forces are calculated for drag cubes, but there seems to be something else.

**Comment by fat-lobyte** [comment]
Thanks for the information!

**Comment by fat-lobyte** [comment]
Commit abc99cab47c21f79173fe132414905ac04fc7b29 might have done something interesting.

Please test with this DLL: https://github.com/neuoy/KSPTrajectories/releases/download/v1.6.9-rc1/Trajectories.dll

**Comment by Charon77** [comment]
@fat-lobyte Hi, I've tried the dll you posted, but it seems to be no difference from the previous version (apart from the rho and actual showing)
However compiling from source works! I now get within 4.1km, using your provided quicksave
Great job!

**Comment by fat-lobyte** [comment]
> However compiling from source works!

Urgh, did I upload the wrong file 🙄 

Thanks for testing! For me, it got within 1.1 km. I'd call that an improvement ;)
What I have noticed is that it's still wildly wrong above 67km, which is fine when your Trajectory is steep, but if it's shallow (like reentering around 3/4 of the globe), this matters.

**Comment by neuoy** [comment]
I also noticed that it's not accurate at high altitudes, this problem is very old, as far as I remember, since the new aerodanymic model (drag cubes etc), there was always a lot of drift of the predicted landing point during the first part of reentry. I have no clue of the root cause though :(

**Comment by fat-lobyte** [comment]
> I have no clue of the root cause though :(

I have 3 ideas, which may all be wrong.

First, it looks like the prediction gets magically accurate pretty much around 67.500m, which is almost exactly the atmosphere cutoff point for the old (pre 1.0.5) atmosphere. Maybe either Trajectories or KSP uses this hardcoded number somewhere (or some kind of float curve doesn't go up that high). Didn't find anything in the code though.

Second, the air up there is so very thin and the velocity very high, so all ratios of functions of these two will be very sensitive to errors. Maybe some approximations are breaking down, or some floats can't represent the numbers well enough.

Third, maybe somehow the cache is set to have a zero force at the edge of the atmosphere, which causes the drag to be way too low. Going lower than 67.5km makes the cache interpolate between different (and more correct) data points. But considering that strange (and inaccurate) things happen when the cache is turned off, this theory is not well supported.

**Comment by fat-lobyte** [comment]
> Going lower than 67.5km makes the cache interpolate between different (and more correct) data points. But considering that strange (and inaccurate) things happen when the cache is turned off, this theory is not well supported.

Actually maybe the cache is part of the problem. With the cache off, I just landed 17.5km off target. That sounds like a lot - until you consider that it was from 3/4 of an orbit away, with gliding through the highest atmosphere layer most of the time.

**Comment by neuoy** [comment]
Maybe worth checking two things : what's the max altitude of the cache, and if increasing its resolution on the altitude axis helps? If it does, maybe it's just a matter of using a log scale (I suppose it's currently linear but I don't actually remember, maybe it's based on air density in which case it's already correct). The velocity scale is already squared.

**Comment by fat-lobyte** [comment]
So I did some more testing, and I'm fairly certain that the wildly incorrect prediction is fixed.

Without the cache, 
For Kerbin, we get an improvement of deviation from 32km down to 1.1km,
for Eve, we get one from 400km down to 22km

I consider that "good enough" for now.
With the cache, it's worse, especially at high altitudes - but at least that's a specific area where I can look into, instead of wild guessing like with this bug.

That's why I consider this bug fixed with commit abc99cab47c21f79173fe132414905ac04fc7b29 . I know that the precision is far from perfect, but at least it's not as "completely wrong" as before.

I will deal with the cache precision errors and with the remaining inaccuracies in new, separate issues.
