### ISSUE TITLE
Update for KSP 1.2.9/1.3.0

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#86]

**Comment by fat-lobyte** [comment]
On first sight, seems to compile and work just fine. I'll keep this open until release if anyone finds incompatibilities.

**Comment by skrelk** [comment]
I tested this in 1.2.2. and it remains compatible

**Comment by sebseb7** [comment]
tested in 1.3 - crashes

(clicked on the blizzybar icon in map view returning from the mun)

[2017-06-11_164524.zip](https://github.com/neuoy/KSPTrajectories/files/1066512/2017-06-11_164524.zip)

**Comment by fat-lobyte** [comment]
@sebseb7  Please create a new issue for crashes

**Comment by fat-lobyte** [comment]
Works well enough in 1.3.0, so I am closing this. Please create new issues for crashes.
