### ISSUE TITLE
Include direction in GUI distance from target

### ISSUE THREAD

**Issue by skrelk** [neuoy/KSPTrajectories#91]
Currently, the GUI displays the difference between the targeted landing point and the projected impact point. Could this be enhanced by adding the direction of this deviation, for example 5 km from target from heading 030, or 5 km total from target, 3 km laterally, 2 km longitudinally.

**Comment by fat-lobyte** [comment]
> or 5 km total from target, 3 km laterally, 2 km longitudinally.

This would be fairly trivial to implement,

>  for example 5 km from target from heading 030

This might require a bit of math, and I'm not sure how hard that math would be.

**Comment by skrelk** [comment]
Something like +/- lat/lon would be good. As long as it provides an idea of where to steer

**Comment by skrelk** [comment]
this has been implemented, so I'm closing the issue
